### ISSUE TITLE
Files containing all books

### ISSUE THREAD

**Issue by Leonard907** [lilakk/BooookScore#5]
Hi

I understand that the books cannot be released due to copyright reasons, but is there anyway that I can get the file containing all the books? One of my work would benefit much from this dataset for evaluation purposes. I would only use this dataset for research purposes and won't make it public. Thank you!

**Comment by lilakk** [comment]
What's your preferred email address? I will email the dataset to you

**Comment by Leonard907** [comment]
@lilakk  Either ou_litu@163.com and l.ou-1@sms.ed.ac.uk is fine. Thank you very much!

**Comment by lilakk** [comment]
Sent to the second address!
