### ISSUE TITLE
Can still apply for access to the dataset for this study?

### ISSUE THREAD

**Issue by CxsGhost** [lilakk/BooookScore#6]
Hello, it seems that the application form cannot be filled out again as it shows no permission.
Can I still obtain access to this research dataset?
thank!

**Comment by lilakk** [comment]
Apologies, that was a mistake! You can try again now, thanks!

**Comment by CxsGhost** [comment]
Hello, thank you again for your excellent work! I have submitted two data access application forms, but have not received a response yet. Could you kindly push forward?

**Comment by lilakk** [comment]
Ah so sorry about this, somehow Google forms was not notifying me about new submissions. I just emailed you the dataset!
